<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class AdvancedDatabaseOperationsController extends Controller
{
    /**
     * Q1: Reservations Table Data
     */
    public function reservations(): JsonResponse
    {
        $reservations = DB::select('SELECT * FROM `Reservations` ORDER BY `ResID` DESC');

        return response()->json([
            'success' => true,
            'question' => 'Q1',
            'title' => 'Reservations Table (PK, FK, UNIQUE, CHECK Constraints)',
            'data' => $reservations
        ]);
    }

    /**
     * Q6: View - OutstandingBookings
     */
    public function outstandingBookings(): JsonResponse
    {
        $results = DB::select('SELECT * FROM `OutstandingBookings` ORDER BY `travel_date` ASC');

        return response()->json([
            'success' => true,
            'question' => 'Q6',
            'title' => 'OutstandingBookings (VIEW with Aggregate & CASE)',
            'data' => $results
        ]);
    }

    /**
     * Q7: Stored Procedure - sp_TravelerBookingStatus
     */
    public function travelerBookingStatus(int $id): JsonResponse
    {
        $results = DB::select('CALL sp_TravelerBookingStatus(?)', [$id]);

        return response()->json([
            'success' => true,
            'question' => 'Q7',
            'title' => 'sp_TravelerBookingStatus (PROCEDURE with IF/ELSE & CASE)',
            'data' => $results
        ]);
    }

    /**
     * Q8: Stored Procedure - sp_ReviewPackages
     */
    public function reviewPackages(): JsonResponse
    {
        $results = DB::select('CALL sp_ReviewPackages()');
        $updatedPackages = DB::select('SELECT id, title, price, status FROM packages ORDER BY id');

        return response()->json([
            'success' => true,
            'question' => 'Q8',
            'title' => 'sp_ReviewPackages (PROCEDURE with WHILE Loop & Conditional Updates)',
            'logs' => $results,
            'packages' => $updatedPackages
        ]);
    }

    /**
     * Q9: Trigger Audit Log - package_audit
     */
    public function packageAuditLog(): JsonResponse
    {
        $results = DB::select('SELECT * FROM `package_audit` ORDER BY `id` DESC LIMIT 50');

        return response()->json([
            'success' => true,
            'question' => 'Q9',
            'title' => 'package_audit (Populated by trg_package_price_audit Trigger)',
            'data' => $results
        ]);
    }

    /**
     * Q9 Tester: Modify package price or status to test trigger live
     */
    public function testTriggerPriceUpdate(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'package_id' => 'required|integer',
            'new_price' => 'required|numeric|min:1',
            'new_status' => 'nullable|string|in:draft,published,archived'
        ]);

        $pkgId = $validated['package_id'];
        $newPrice = $validated['new_price'];
        $newStatus = $validated['new_status'] ?? null;

        $oldPackage = DB::table('packages')->where('id', $pkgId)->first();

        if (!$oldPackage) {
            return response()->json([
                'success' => false,
                'message' => 'Package not found'
            ], 404);
        }

        $updateData = ['price' => $newPrice];
        if ($newStatus) {
            $updateData['status'] = $newStatus;
        }

        DB::table('packages')->where('id', $pkgId)->update($updateData);

        // Fetch latest audit record for this package
        $latestAudit = DB::table('package_audit')
            ->where('package_id', $pkgId)
            ->orderBy('id', 'desc')
            ->first();

        return response()->json([
            'success' => true,
            'message' => 'Package updated successfully. Trigger fired and logged to package_audit!',
            'old_values' => [
                'price' => $oldPackage->price,
                'status' => $oldPackage->status
            ],
            'audit_entry' => $latestAudit
        ]);
    }

    /**
     * Guide Notifications generated by trg_booking_notify_guide trigger
     */
    public function notifications(): JsonResponse
    {
        $notifications = DB::select('SELECT * FROM `notifications` ORDER BY `notification_id` DESC LIMIT 20');

        return response()->json([
            'success' => true,
            'title' => 'Guide Notifications (Generated by trg_booking_notify_guide Trigger)',
            'data' => $notifications
        ]);
    }

    /**
     * Q10: Transaction Procedure - sp_CreateBookingWithPayment
     */
    public function createBookingTransaction(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'traveler_id' => 'required|integer',
            'package_id' => 'required|integer',
            'travel_date' => 'required|date',
            'travelers' => 'required|integer|min:1|max:20',
            'amount' => 'required|numeric|min:1',
        ]);

        $results = DB::select('CALL sp_CreateBookingWithPayment(?, ?, ?, ?, ?)', [
            $validated['traveler_id'],
            $validated['package_id'],
            $validated['travel_date'],
            $validated['travelers'],
            $validated['amount'],
        ]);

        $latestBooking = DB::table('bookings')->orderBy('booking_id', 'desc')->first();
        $latestPayment = DB::table('payments')->orderBy('payment_id', 'desc')->first();

        return response()->json([
            'success' => true,
            'question' => 'Q10',
            'title' => 'sp_CreateBookingWithPayment (TRANSACTION + SAVEPOINT + HANDLERS)',
            'result' => $results,
            'booking' => $latestBooking,
            'payment' => $latestPayment
        ]);
    }

    /**
     * Get Raw SQL Lecture Codes (MySQL and T-SQL)
     */
    public function rawSql(): JsonResponse
    {
        $mysqlPath = database_path('queries/advanced_database_operations.sql');
        $tsqlPath = database_path('queries/advanced_database_operations_tsql.sql');

        $mysqlSql = File::exists($mysqlPath) ? File::get($mysqlPath) : '';
        $tsqlSql = File::exists($tsqlPath) ? File::get($tsqlPath) : '';

        return response()->json([
            'success' => true,
            'mysql_sql' => $mysqlSql,
            'tsql_sql' => $tsqlSql
        ]);
    }
}
